# Generated by Django 6.1.1 on 2026-10-08 14:09

from django.db import migrations, models


FORWARD = {'draft': 'pending', 'completed': 'delivered'}
BACKWARD = {'pending': 'draft', 'delivered': 'completed', 'on_the_way': 'confirmed'}


def convert(mapping):
    def run(apps, schema_editor):
        Order = apps.get_model('sales', 'Order')
        for old, new in mapping.items():
            Order.objects.filter(status=old).update(status=new)
    return run


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
        migrations.RunPython(convert(FORWARD), convert(BACKWARD)),
    ]
